---
- name: Ensure repositories are cloned locally
  git: repo={{ item.repo_url }} dest={{ webapps_dir }}/{{ item.app_name }} remote={{ repo_remote }} version={{ repo_version }}
  with_items:
    - { repo_url: 'https://github.com/TheSophon/sophon.git', app_name: 'sophon' }
    - { repo_url: 'https://github.com/TheSophon/sophon-webapp.git', app_name: 'sophon-webapp' }

- name: Ensure Python-mysqldb is installed
  apt: name=python-mysqldb state=present

- name: Ensure pip and setuptools is latest
  pip: name={{ item.package_name }} virtualenv={{ webapps_dir }}/{{ item.app_name }}/venv state=latest
  with_items:
    - { app_name: "sophon", package_name: "pip" }
    - { app_name: "sophon", package_name: "setuptools" }

- name: Ensure Sophon is installed
  pip: name=file://{{ webapps_dir }}/{{ item.app_name }} virtualenv={{ webapps_dir }}/{{ item.app_name }}/venv state=present virtualenv_site_packages=yes
  with_items:
    - { app_name: "sophon" }

- name: Ensure database has been created
  mysql_db: name=sophon state=present

- name: Ensure dependencies of sophon-web is installed 
  npm: path={{ webapps_dir }}/{{ item.app_name }} registry=http://registry.cnpmjs.org/
  with_items:
    - { app_name: "sophon-webapp" }

- name: Ensure Supervisor has been configured well
  copy: src=./roles/ansible-role-sophon/files/supervisor/{{ item }} dest=/etc/supervisor/conf.d/
  with_items:
    - "sophon.conf"
    - "sophon-cron.conf"

- name: Ensure sophon-web is built
  command: npm run build chdir={{ webapps_dir }}/{{ item.app_name }}
  with_items:
    - { app_name: "sophon-webapp" }

- name: Stop app
  supervisorctl: name={{ item }} state=stopped
  with_items:
    - "sophon"
    - "sophon-cron"

- name: Ensure Nginx has been configured well
  copy: src=./roles/ansible-role-sophon/files/nginx/{{ item }} dest=/etc/nginx/conf.d/
  with_items:
    - "sophon.conf"

- name: Ensure public key has been placed
  copy: src={{ local_public_key_directory_path }}/{{ public_key_filename }} dest={{ remote_public_key_directory_path }}/{{ public_key_filename }}

- name: Ensure init_db.py has been placed
  template: src=./roles/ansible-role-sophon/files/init_db/init_db.j2 dest=/tmp/init_db.py

- name: Ensure database has been initialized
  command: /{{ webapps_dir }}/{{ item }}/venv/bin/python /tmp/init_db.py
  with_items:
    - "sophon"

- name: Restart app
  supervisorctl: name={{ item }} state=restarted
  with_items:
    - "sophon"
    - "sophon-cron"

- name: Restart Nginx
  service: name=nginx state=restarted
