---
# From https://github.com/geerlingguy/ansible-role-nodejs/blob/master/tasks/setup-Debian.yml
- name: Ensure apt-transport-https is installed
  apt: name=apt-transport-https state=present

- name: Ensure Nodesource apt key has been added
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Ensure NodeSource repositories for Node.js has been added
  apt_repository: repo={{ item }} state=present
  with_items:
    - "deb https://deb.nodesource.com/node_6.x jessie main"
    - "deb-src https://deb.nodesource.com/node_6.x jessie main"

- name: Ensure Node.js and npm are installed
  apt: name=nodejs state=present update_cache=yes
